	<footer id="footer" class="dark">
			<div class="container">
		
				<!-- Footer Widgets
				============================================= -->
				<div class="footer-widgets-wrap">
		
					<div class="row col-mb-50">
						<div class="col-lg-12">
		
							<div class="row col-mb-50">
								<div class="col-md-3">
		
									<div class="widget clearfix">
		
										<img src="../images/FCAblanco.png" alt="Image" class="footer-logo">
		
										<p><strong>Universidad Autónoma de Baja California</strong> Facultad de Ciencias Administrativas</p>
		
										<div style="background: url('../images/world-map.png') no-repeat center center; background-size: 100%;">
											<address>
												<strong>Dirección:</strong><br>
												 Blvd. Río Nuevo y Eje Central Colonia Agualeguas <br>
												Mexicali, Baja California C.P. 21330
											</address>
											<strong>Teléfono:</strong></abbr> 686-841-82-22 Extensión 45003<br>
											<strong>Email: </strong></abbr>direccion.fcamxl@uabc.edu.mx
										</div>
		
									</div>
		
								</div>
		
		
								<div class="col-md-3">

									<div class="widget widget_links clearfix">

										<h4>Enlaces Institucionales</h4>

										<ul>
											<li><a href="https://uabc.blackboard.com/" target="_blank">Blackboard</a></li>
											<li><a href="https://mail.google.com/a/uabc.edu.mx" target="_blank">Correo</a></li>
												<li><a href="https://www.uabc.mx/" target="_blank">UABC</a></li>
										</ul>

									</div>

								</div>
								<div class="col-md-3">

									<div class="widget widget_links clearfix">

										<h4>Enlaces de interés </h4>

										<ul>
											<li><a href="https://fundacionuabc.org/" target="_blank">Fundación UABC, A.C.</a></li>
											<li><a href="http://www.cgvca.uabc.mx/home/es/mision/#" target="_blank">Intercambio</a></li>
											<li><a href="https://www.sorteosuabc.mx/" target="_blank">Sorteos</a></li>
											<li><a href="http://admisiones.celexbc.com.mx/" target="_blank">UNISER, A.C.</a></li>
										</ul>

									</div>

								</div>
								<div class="col-md-3">

									<div class="widget widget_links clearfix">

										<h4>Otras Aplicaciones</h4>

										<ul>
											<li><a href="https://alumnos.uabc.mx/web/alumnos/bienvenido" target="_blank">Portal de Alumnos</a></li>
											<li><a href="https://academicos.uabc.mx/" target="_blank">Portal Docente</a></li>
										</ul>

									</div>

								</div>								
							</div>
		
						</div>
					</div>
		
				</div><!-- .footer-widgets-wrap end -->
		
			</div>
		
			<!-- Copyrights
			============================================= -->
			<div id="copyrights">
				<div class="container">
		
					<div class="row col-mb-30">
		
						<div class="col-md-6 text-center text-md-start">
							Copyrights &copy; 2022 Facultad de Ciencias Administrativas.<br>
						</div>
		
						<div class="col-md-6 text-center text-md-end">
							<div class="d-flex justify-content-center justify-content-md-end">
								<a href="https://www.facebook.com/fca.mexicali" target="_blank" class="social-icon si-small si-borderless si-facebook">
									<i class="icon-facebook"></i>
									<i class="icon-facebook"></i>
								</a>
		
							<!-- 	<a href="#" class="social-icon si-small si-borderless si-twitter">
									<i class="icon-twitter"></i>
									<i class="icon-twitter"></i>
								</a>
		
								<a href="#" class="social-icon si-small si-borderless si-gplus">
									<i class="icon-gplus"></i>
									<i class="icon-gplus"></i>
								</a>
		
								<a href="#" class="social-icon si-small si-borderless si-pinterest">
									<i class="icon-pinterest"></i>
									<i class="icon-pinterest"></i>
								</a>
		
								<a href="#" class="social-icon si-small si-borderless si-vimeo">
									<i class="icon-vimeo"></i>
									<i class="icon-vimeo"></i>
								</a>
		
								<a href="#" class="social-icon si-small si-borderless si-github">
									<i class="icon-github"></i>
									<i class="icon-github"></i>
								</a>
		
								<a href="#" class="social-icon si-small si-borderless si-yahoo">
									<i class="icon-yahoo"></i>
									<i class="icon-yahoo"></i>
								</a>
		
								<a href="#" class="social-icon si-small si-borderless si-linkedin">
									<i class="icon-linkedin"></i>
									<i class="icon-linkedin"></i>
								</a> -->
							</div>
		
							<div class="clear"></div>
		
							<!-- <i class="icon-envelope2"></i> info@canvas.com <span class="middot">&middot;</span> <i class="icon-headphones"></i> +1-11-6541-6369 <span class="middot">&middot;</span> <i class="icon-skype2"></i> CanvasOnSkype -->
						</div>
		
					</div>
		
				</div>
			</div><!-- #copyrights end -->
		</footer>