<!DOCTYPE html>
<html dir="ltr" lang="en-US">
<head>

	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="author" content="SemiColonWeb" />

	<!-- Stylesheets
	============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,400i,700|Poppins:300,400,500,600,700|PT+Serif:400,400i&display=swap" rel="stylesheet" type="text/css" />
	<link rel="stylesheet" href="../css/bootstrap.css" type="text/css" />
	<link rel="stylesheet" href="../style.css" type="text/css" />
	<link rel="stylesheet" href="../css/dark.css" type="text/css" />
	<link rel="stylesheet" href="../css/font-icons.css" type="text/css" />
	<link rel="stylesheet" href="../css/animate.css" type="text/css" />
	<link rel="stylesheet" href="../css/magnific-popup.css" type="text/css" />

	<link rel="stylesheet" href="../css/custom.css" type="text/css" />
	<link rel="stylesheet" href="../css/colors.css">
	<link rel="stylesheet" href="css/font-icons.css" type="text/css" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />

	<!-- Document Title
	============================================= -->
	<title>Directorio | Facultad de Ciencias Administrativas</title>

</head>

<body class="stretched page-transition" data-loader="2" data-animation-in="fadeIn" data-speed-in="1500" data-animation-out="fadeOut" data-speed-out="800">

	<!-- Document Wrapper
	============================================= -->
	<div id="wrapper" class="clearfix">

		<!-- Header
		============================================= -->
		<header id="header" class="" data-sticky-logo-height="74" data-menu-padding="32">
			<div id="header-wrap">
				<div class="container">
					<div class="header-row">
						<!-- Logo
						============================================= -->
						<div id="logo">
							<a href="../index.html" class="standard-logo" data-dark-logo="images/logo-dark.png"><img  src="../images/uabcfca.png" alt="Canvas Logo"></a>
							<a href="../index.html" class="retina-logo" data-dark-logo="images/logo-dark@2x.png"><img  src="../images/uabcfca.png" alt="Canvas Logo"></a>
						</div><!-- #logo end -->
		
		
						<div id="primary-menu-trigger">
							<svg class="svg-trigger" viewBox="0 0 100 100"><path d="m 30,33 h 40 c 3.722839,0 7.5,3.126468 7.5,8.578427 0,5.451959 -2.727029,8.421573 -7.5,8.421573 h -20"></path><path d="m 30,50 h 40"></path><path d="m 70,67 h -40 c 0,0 -7.5,-0.802118 -7.5,-8.365747 0,-7.563629 7.5,-8.634253 7.5,-8.634253 h 20"></path></svg>
						</div>
		
						<!-- Primary Navigation
						============================================= -->
						<!-- #primary-menu end -->
						<nav class="primary-menu sub-title">
		
							<ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="../institucional.html"><div>Institucional</div></a>
 									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#direccion"><div>Dirección</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#subdireccion"><div>Subdirección</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#administracion"><div>Administración</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#organigrama"><div>Organigrama</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#manual"><div>Manual de Funciones</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://web.uabc.mx/formacionbasica/modeloedu.htm" target="_blank"><div>Modelo Educativo</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#formatos"><div>Formatos ACRED.</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../institucional.html#video"><div>Video FCA</div></a>
										</li>										
									</ul>
								</li>
							</ul>
						
                            <ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="#"><div>Oferta Educativa</div></a>
									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="../licenciaturas/lc.html"><div>Licenciado en Contaduría</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../licenciaturas/lae.html"><div>Licenciado en Administración de Empresas</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../licenciaturas/li.html"><div>Licenciado en Informática / Licenciado en Inteligencia de Negocios</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../licenciaturas/lm.html"><div>Licenciado en Mercadotecnia</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../licenciaturas/lni.html"><div>Licenciado en Negocios Internacionales</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../licenciaturas/lgt.html"><div>Licenciado en Gestión Turística</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://fca.mxl.uabc.mx/posgrado/" target="_blank"><div>Posgrado</div></a>
										</li>
									</ul>
								</li>
							</ul>							
														<ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="index.html"><div>Alumnos</div></a>
									<ul class="sub-menu-container">
										
										<li class="menu-item">
											<a class="menu-link" href="https://sibecas.uabc.mx/login" target="_blank"><div>Portal de Becas</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="https://uabc.blackboard.com/" target="_blank"><div>Portal Blackboard</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://catalogocimarron.uabc.mx/" target="_blank"><div>Portal de Biblioteca</div></a>
										</li>
										
										<li class="menu-item">
											<a class="menu-link" href="http://emprendedores.fcauabc.com" target="_blank"><div>Portal de Emprendedores</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://admisiones.celexbc.com.mx/" target="_blank"><div>Portal de Idioma Extranjero</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://www.cgvca.uabc.mx/home/es/mision/#" target="_blank"><div>Portal de Intercambio</div></a>
										</li>
										
										<li class="menu-item">
											<a class="menu-link" href="https://alumnos.uabc.mx/web/alumnos/bienvenido" target="_blank"><div>Portal de Alumnos</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="https://sifpvu.uabc.mx/" target="_blank"><div>Portal de Prácticas/PVCC</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="#"><div>Servicio Social</div></a>
											<ul class="sub-menu-container">
												<li class="menu-item">
													<a class="menu-link" target="_blank" href="../alumnos/servicio-social-comunitario.html"><div>Comunitario</div></a>
												</li>
												<li class="menu-item">
													<a class="menu-link" target="_blank" href="../alumnos/servicio-social-profesional.html"><div>Profesional</div></a>
												</li>
											</ul>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="https://tutorias.uabc.mx" target="_blank"><div>Portal Tutorias</div></a>
										</li>	
										<li class="menu-item">
											<a class="menu-link" href="../alumnos/reinscripciones-horarios-calendario.html" target="_blank"><div>	Reinscripciones, Horarios y Calendario de Exámenes...</div></a>
										</li>	
										<li class="menu-item">
											<a class="menu-link" href="../alumnos/titulacion.html" target="_blank"><div>Titulación</div></a>
										</li>
																				<!--sub-menu aspirantes 05/10/2022  -->
										<li class="menu-item">
											<a class="menu-link" href="#"><div>Nuevo Ingreso</div></a>
											<ul class="sub-menu-container">
												<li class="menu-item">
													<a class="menu-link" href="../curso-induccion.html"><div>Curso de Inducción</div></a>
												</li>
												<li class="menu-item">
													<a class="menu-link" href="../curso-prop.html"><div>Curso de Propedéutico</div></a>
												</li>
												<li class="menu-item">
													<a class="menu-link" href="https://admisiones.uabc.mx/" target="_blank"><div>Convocatoria</div></a>
												</li>										
											</ul>
										</li>
										<!-- fin sub-menu aspirantes -->										
									</ul>
								</li>
							</ul>

							<ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="https://academicos.uabc.mx/" target="_blank"><div>Académicos</div></a>
									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="../documentos/ACRED-143.docx" target="_blank" download><div>Criterios de evaluación 2022-2</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="https://ed.uabc.mx" target="_blank"><div>Portal Evaluación Docente</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="https://sifodd.uabc.mx/" target="_blank"><div>Portal de Formación Docente</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://siii.uabc.mx" target="_blank"><div>Portal SIII-UABC</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://siifca.uabc-fca.com/" target="_blank"><div>Portal SIII-FCA</div></a>
										</li>
									</ul>
								</li>
							</ul>
							<ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="#"><div>Vinculación</div></a>
									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="../vinculacion/index.html#bolsa"><div>Bolsa de Trabajo</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../vinculacion/index.html#egresados"><div>Egresados</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../vinculacion/index.html#educont"><div>Educación Continua</div></a>
										</li>		
										<li class="menu-item">
											<a class="menu-link" href="../vinculacion/index.html#radio"><div>Radio</div></a>
										</li>									
									</ul>
								</li>
							</ul>	
							<ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="index.html"><div>Directorio</div></a>
									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="https://www.uabc.mx/directorio/" target="_blank"><div>UABC</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="#"><div>FCA por áreas</div></a>
										</li>										
									</ul>
								</li>
							</ul>		
							<ul class="menu-container">
								<li class="menu-item">
									<a class="menu-link" href="#"><div>Transparencia</div></a>
									<ul class="sub-menu-container">
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#informes"><div>Informes</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#plan"><div>Plan de Desarrollo Institucional (FCA)</div></a>
										</li>							
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#organos"><div>Órganos Colegiados (Consejos)</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#convenios"><div>Convenios</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#normativa"><div>Normativa FCA</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#oficios"><div>Oficios</div></a>
										</li>
										<li class="menu-item">
											<a class="menu-link" href="http://transparencia.uabc.mx/Aviso_Privacidad/index.html" target="_blank"><div>Aviso de Privacidad</div></a>
										</li>	
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#convocatorias"><div>Convocatorias</div></a>
										</li>		
										<li class="menu-item">
											<a class="menu-link" href="../transparencia/index.html#consejo"><div>Consejo de Vinculación</div></a>
										</li>
									</ul>
								</li>
							</ul>				
						</nav>
						
		<!-- 
						<form class="top-search-form" action="search.html" method="get">
							<input type="text" name="q" class="form-control" value="" placeholder="Type &amp; Hit Enter.." autocomplete="off">
						</form> -->
		
					</div>
				</div>
			</div>
		   
			
		</header>